version: '3.8'

services:
  api-gateway:
    image: nginx:1.23
    ports:
      - "80:80"
    volumes:
      - ./api-gateway/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - user-service

  user-service:
    build:
      context: ./user-service
      args:
        RUN_TESTS: ${RUN_TESTS:-false}  # Добавляем эту строку
    environment:
      DB_URI: "postgresql://user:password@db/userdb"
      SECRET_KEY: "supersecretkey"
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: